### ISSUE TITLE
Looking for an example call to get every book in library.

### ISSUE THREAD

**Issue by cjemorton** [omarroth/audible.cr#4]
Question:

Just looking for a little clarification.

When I call `puts client.get("/1.0/library").body` it doesn't seem to return everything in my whole library. It seems to be limited to 99 items in the json response.
- I have over 450+ books in my library.

Looking at the docs from [here](https://github.com/omarroth/audible.cr#get-10library)

Can you give me an example for how to use `page: \d+`?
- I'm unsure what '\d+' actually means.
- How would I go about requesting a specific page, or all the pages, for my whole library?

For this as well - `num_results: \d+ (max: 1000)`.
- Just looking for some examples on how to go about calling different parameters listed in the docs.

I was able to call different `?response_groups=` by appending them to the call by following your example. `/1.0/catalog/products/B002V02KPU?response_groups=product_plan_details,media,review_attrs`

---

The little project I'm actually working on using your library is [here](https://github.com/clem16/audible.cr-build)

My "Scratch File" for this is: [here](https://github.com/clem16/audible.cr-build/blob/master/getlibrary.cr) (It may change as I try things).

Thanks.

**Comment by omarroth** [comment]
Apologies if that isn't clear. `\d+` is a [regular expression](https://stackoverflow.com/a/4235922) which matches one or more digits. So `1`, `91`, `871`, are all valid (up to the max number of `1000` items).

In your case you could use
```crystal
puts client.get("/1.0/library?max_results=450").body
```
to get all the books in your library. If you had 1500 books, for example, you could use
```crystal
puts client.get("/1.0/library?max_results=1000&page=1").body
puts client.get("/1.0/library?max_results=1000&page=2").body # To get the last 500 books
```

Audible uses the provided patterns on their end to validate input, which is why they're provided in the docs as-is. In most cases the provided patterns are mostly straight-forward, the most involved one I can see from skimming the docs is `\d+(,\d+)*` which means `one or more groups of one or more digits separated by commas`. So `10`, `1882,99891,124351`, etc.

Hope that helps.

**Comment by cjemorton** [comment]
Yes! That helps enormously. 

- It looked suspiciously like a regular expression. I just wasn't sure how it could possibly be. It seemed to be out of context. Shifting my perspective to the endpoint, I could see how from Audibles end, a regular expression makes sense to validate the incoming calls.

Is it possible to make a note of this in the doc's? 
I've been pouring over them for days. They are so far the best resource I've found on this subject.

Thanks
